### ISSUE TITLE
[REQUEST] Support for Fruit Trees

### ISSUE THREAD

**Issue by brnbrd** [Kitteh6660/DramaticDoors#10]
https://www.curseforge.com/minecraft/mc-mods/fruit-trees

Fruit Trees is a popular mod adding two wood types, and thus two doors:

**Citrus** and
**Cherry**

Assets can be found here:
https://github.com/Snownee/FruitTrees/tree/1.19-forge/src/main/resources/assets/minecraft/textures/block/fruittrees

**Comment by Kitteh6660** [comment]
Thanks, will look into adding support!

**Comment by Kitteh6660** [comment]
Mod support will be added in mod version 2.1.8 for Minecraft 1.18.2 and 1.19.2.
