### ISSUE TITLE
[BUG] Water on doors and fence gates doesn't flood out

### ISSUE THREAD

**Issue by lzm11111111** [Kitteh6660/DramaticDoors#101]
Descriptions
When place a door on the water, break the block next to water doesn't make the water flood out.

![2024-08-02_13 48 04](https://github.com/user-attachments/assets/032a7712-72e0-4079-9d3e-066fd7e54aa2)

**Comment by Kitteh6660** [comment]
Should be fixed in mod version 3.2.8 for Minecraft 1.20.1. Fix is also planned to be backported to 1.19.2 as well as ported to 1.21.1 too.
