### ISSUE TITLE
Crashes with Dawn of Time

### ISSUE THREAD

**Issue by Hannahbal92** [Kitteh6660/DramaticDoors#102]
Crash with Dawn of Time - Builder Edition.
Both work when only one of the mods are added, but not with eachother.
Have reported to them as well, but according to them there's nothing they can do about it, so sending it in here too.

Whole modpack: https://gist.github.com/Hannahbal92/655bd23487d3fba1dcc89978d56b52e1
Only DD+DoT: https://gist.github.com/Hannahbal92/cfb0d49e6219a7687f5d89aaa56fe6d4

**Important Information**
Minecraft Version: 1.20.1
Mod Loader System: Forge 47.2.0
DramaticDoors Version: 3.2.1-3.2.3 (tried all of them)

**Describe the bug**
Incompatible with Dawn of Time - Builder Edition.

**To Reproduce**
Add both mods

**Expected behavior**
Hoped they would be compatible

**Comment by Kitteh6660** [comment]
It's the result of Dawn of Time Builder Edition changing the codebase. The fix is being tested.

**Comment by Kitteh6660** [comment]
The fix is going to be live in mod version 3.2.5 for 1.20.1.
