### ISSUE TITLE
[BUG]Two Bugs in One Issue

### ISSUE THREAD

**Issue by An-thracene** [Kitteh6660/DramaticDoors#104]
Minecraft Version: 1.20.1
Mod Loader System: Fabric
DramaticDoors Version: 3.2.3

Bug 1: Redlove sliding door of Fruitful Fun
**Describe the bug**
Tall redlove sliding door doesn't behave like the original one.

**To Reproduce**
Place the tall sliding door on the floor and open it.

**Expected behavior**
The sliding door should behave like the train door of Create but without animation.

**Screenshots**
![2024-09-15 012316](https://github.com/user-attachments/assets/d4d8848b-b438-41e6-9645-0eecebdb1bae)
![2024-09-15 012332](https://github.com/user-attachments/assets/72e15523-0205-411f-971c-5fdc4ea231a9)

Bug 2: Tall train door of Create
**Describe the bug**
Tall train door doesn't open like the original one when the train arrives at a station.

**To Reproduce**
Create a train with a tall train door and let the train arrive at a station.

**Expected behavior**
The tall train door should open when the train arrives at the station.

**Comment by Kitteh6660** [comment]
Thanks for reporting, I may look into it! Fixing the tall sliding Cherry door can be done. As for the tall Create train doors, I may try to experiment with a fix.

For now, you can try using redstone signal as workaround.

**Comment by Kitteh6660** [comment]
Good news: the tall sliding Redlove door will be fixed in the new update. They also get the corrected hitbox.

As for tall Create sliding doors, I am still working on a fix to make them properly open and close.

**Comment by Kitteh6660** [comment]
Should be fixed in mod version 3.2.8 for 1.20.1.
