### ISSUE TITLE
[REQUEST] Support for Pyromancer

### ISSUE THREAD

**Issue by brnbrd** [Kitteh6660/DramaticDoors#11]
https://www.curseforge.com/minecraft/mc-mods/pyromancer

Pyromancer is a popular mod adding one wood type, and thus one door:

**Pyrowood**
https://media.forgecdn.net/attachments/394/424/pyrowoodstuff.png

**Comment by Kitteh6660** [comment]
I can easily do that. Expect support in version 2.1.8 of the mod!

**Comment by Kitteh6660** [comment]
Mod support will be added in version 2.1.8 for Minecraft 1.18.2 and 1.19.2.
