### ISSUE TITLE
[BUG] Crash when Zombie checks tall door

### ISSUE THREAD

**Issue by Happyfrozenfire** [Kitteh6660/DramaticDoors#12]
Gist: https://gist.github.com/Happyfrozenfire/af1e9fe92f3084a8a9ef37121ec53261

Minecraft Version: **1.19.2**
Fabric Version: **0.4.10**
DramaticDoors Version: **1.3.3**

When a Zombie checks a tall door to break it on Hard difficulty, the server crashes. The following line is contained in all four console logs:
`	at net.minecraft.class_1343.handler$beh000$injectIsDoorOpen(class_1343.java:531) ~[server-intermediary.jar:?]`

**To Reproduce**
1. Create a box with 1x3 space with a hole for zombies on one end and a hole for yourself on the other end.
2. Place a tall door of any variety from the zombie's side.
3. Spawn zombies in the zombie hole until they start cramming to ensure you get one capable of breaking doors.
4. Go into survival mode and jump in the hole.
5. AFK until crash.

**Expected behavior**
The zombie should begin breaking the door. Instead, the zombie causes a server crash.

**Comment by Kitteh6660** [comment]
I will look into it, thanks.

**Comment by Kitteh6660** [comment]
Great news! A fix has been released. Please use version 1.4.0_1 of Dramatic Doors for Fabric and discontinue using old versions.

**Comment by Clickism** [comment]
Hey! I have the same issue but on Forge, is there a fix for this on Forge?
I can send the log files and details if you want.

**Comment by Kitteh6660** [comment]
I will bring the fix over to Forge shortly!

**Comment by Kitteh6660** [comment]
The fix has been implemented as of version 2.1.9 of Dramatic Doors for Forge. The fix will also be backported to 1.18.2.

**Comment by Kitteh6660** [comment]
The fix has been backported to 1.18.2 on Forge. Issue is now closed.
