### ISSUE TITLE
[REQUEST] Make NPCs open two doors at a time

### ISSUE THREAD

**Issue by kennylux** [Kitteh6660/DramaticDoors#15]
**Is your feature request related to a problem? Please describe.**
My villagers only open 1 door out of two

**Describe the solution you'd like**
Make NPCs (e.g. villagers) open/close both doors instead of just one

This would be a nice little addition to the mod

**Comment by Kitteh6660** [comment]
Implemented as of mod version 2.1.9 of Dramatic Doors for Forge on 1.19.2. I will look to backport the changes to 1.18.2.
