### ISSUE TITLE
[BUG] Crash with ConsistencyPlus and DramaticDoors on Quilt

### ISSUE THREAD

**Issue by DaveyL2013** [Kitteh6660/DramaticDoors#16]
**Important Information**
Minecraft Version: **1.19.2**
Quilt Version: **0.18.1-beta.58**
DramaticDoors Version: **Fabric-1.19.2-1.4.0**
C+ Version: **fabric-0.5.1+1.19.2**

**Describe the bug**
Having both ConsistencyPlus and DramaticDoors installed on Quilt causes Minecraft to fail to load due to minecraft:air having a duplicate waterlogged property... *somehow*

**To Reproduce**
Install Quilt
Install ConsistencyPlus and DramaticDoors (+ QSL & Architectury, tested both with and without other unrelated mods)
Try to start Minecraft

**Expected behavior**
The game... *doesn't* crash from the air being to moist <sub><sup>(that's a joke obviously)</sup></sub>

**Logs**
https://mclo.gs/QFLPaEp

**Comment by DaveyL2013** [comment]
Paired Issue: https://github.com/ConsistencyPlus/ConsistencyPlus/issues/146

**Comment by TropheusJ** [comment]
Dramatic doors is adding waterlogability to vanilla blocks, which is *extremely* dangerous, as seen here.
[fence gates](https://github.com/Kitteh6660/DramaticDoors/blob/93eecfff6f85948e33dd62841b62364567aae4ab/src/main/java/com/fizzware/dramaticdoors/mixin/FenceGateBlockMixin.java#L36) and [doors](https://github.com/Kitteh6660/DramaticDoors/blob/93eecfff6f85948e33dd62841b62364567aae4ab/src/main/java/com/fizzware/dramaticdoors/mixin/DoorBlockMixin.java#L41)
This is not a C+ issue, and this will crash with any mod that adds waterloggable fence gates or doors.

**Comment by TropheusJ** [comment]
[Statement](https://github.com/Virtuoel/Statement) should be used for adding to vanilla states. Adding states like this also causes other problems, which Statement avoids, and it should fix this too.

**Comment by Kitteh6660** [comment]
Update to 1.4.0_1, this should fix the issues.
