### ISSUE TITLE
[REQUEST] Compatibility with Quark's new Bamboo doors

### ISSUE THREAD

**Issue by LolJohn11** [Kitteh6660/DramaticDoors#17]
**Is your feature request related to a problem? Please describe.**
In one of the recent updates, the [Quark](https://www.curseforge.com/minecraft/mc-mods/quark) mod has added backported bamboo "wood" type into the mod, which includes a bamboo door. Right now, Dramatic Doors mod doesn't have a tall bamboo door variant.

**Describe the solution you'd like**
I would like for Dramatic Doors to support the newest addition to Quark and have a tall bamboo door variant.

**Comment by Kitteh6660** [comment]
Support is already included as of version 2.1.8 of Dramatic Doors. I switched the compat from One Twenty Backport to Quark when I added Quark's Ancient doors.

Seriously, check out 1.19.2-2.1.8 change log!
