### ISSUE TITLE
Not Entirely Sure[BUG]

### ISSUE THREAD

**Issue by ArrowSunflower** [Kitteh6660/DramaticDoors#18]
My friend's server receives this error when trying to boot up with dramatic doors.

@Inject(@At("INVOKE")) Shift.BY=2 on dramaticdoors.micins.json:OpenDoorsTaskMixin from mod dramaticdoors: :handler$bhm000$injectStartP1 exceeds the maxium allowed value: 0. Increase the value of maxShiftBy to suppress this warning

**Comment by Kitteh6660** [comment]
I should look into it. It doesn't crash the server, does it?

**Comment by ArrowSunflower** [comment]
Turns out it wasn't anything mod related, it was on their side, apologies for this.
