### ISSUE TITLE
compatability crash with supplementaries! [BUG]

### ISSUE THREAD

**Issue by netcore10** [Kitteh6660/DramaticDoors#20]
https://github.com/MehVahdJukaar/Supplementaries/issues/513

**Important Information**
Minecraft Version: 1.19.2
quilt/fabric latest Version
DramaticDoors Version: latest

**Describe the bug**
mixin issue supposedly

**Comment by Kitteh6660** [comment]
Try disabling Fence Gate mixin.

**Comment by netcore10** [comment]
how do i do that?

**Comment by netcore10** [comment]
a note from supplementaries: https://github.com/MehVahdJukaar/Supplementaries/issues/513#issuecomment-1428042818

**Comment by Kitteh6660** [comment]
Check the config folder, in the same directory where you also find the mods folder.

From there, look for Dramatic Doors fabric config.

**Comment by Fourbo** [comment]
This worked for me, disabling the fence gate mixin let me update Supplementaries from 2.2.46 to 2.2.50 and not get a crash anymore.

**Comment by Kitteh6660** [comment]
I will also add Statement integration. It will remain an optional dependency but when installed, it improves compatibility.

**Comment by Kitteh6660** [comment]
Should be resolved in mod version 1.4.2 now.
