### ISSUE TITLE
[REQUEST]Support for Terrestria & Cinderscapes

### ISSUE THREAD

**Issue by An-thracene** [Kitteh6660/DramaticDoors#23]
https://beta.curseforge.com/minecraft/mc-mods/terrestria

https://beta.curseforge.com/minecraft/mc-mods/cinderscapes

Terrestria and Cinderscapes are popular mods by Terraformers.
Terrestria adds nine wood types, and Cinderscapes adds two.

**Comment by Kitteh6660** [comment]
I will look into it, thanks!

**Comment by Kitteh6660** [comment]
The mod support will be added in next version of Dramatic Doors Fabric for 1.19.2.

**Comment by Kitteh6660** [comment]
Added support in mod version 1.4.2 for Minecraft 1.19.2, applies to Fabric.
