### ISSUE TITLE
Colorful Azalea compatibility [Feature request]

### ISSUE THREAD

**Issue by Royal-Jelly** [Kitteh6660/DramaticDoors#24]
Colorful azaleas adds 7 new wood/door variants, It is quite shiny and can be found : [here](https://www.curseforge.com/minecraft/mc-mods/colorfulazaleas)

**Comment by Kitteh6660** [comment]
It's already supported for both Forge and Fabric. :)

**Comment by Kitteh6660** [comment]
Actually, I forgot to fix this for Fabric, hang on tight. The assets and items are already in the jar file, just incorrectly configured.

**Comment by Kitteh6660** [comment]
Fixed in mod version 1.4.2 on Fabric.
