### ISSUE TITLE
[BUG] Chipped changed its door IDs

### ISSUE THREAD

**Issue by 800020h** [Kitteh6660/DramaticDoors#32]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove Dramatic Doors to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Important Information**
Minecraft Version: 1.19.2
Mod Loader System: Fabric (probably also Forge)
DramaticDoors Version: 1.19.2-1.4.2

**Describe the bug**
Chipped changed its door IDs, so all the Chipped compat recipes are broken

**To Reproduce**
take a look in game, or in the files

**Expected behavior**
the recipes would work, because they would use the correct IDs

**Screenshots**
![image](https://user-images.githubusercontent.com/100995970/229113333-2c2b5dcb-305b-4589-9767-b9bc1d57b4e7.png)
![image](https://user-images.githubusercontent.com/100995970/229113458-0faf6dac-fec6-43a5-83f4-8f2d5f63e4f6.png)

**Comment by 800020h** [comment]
the IDs for the tall doors should probably be changed too

**Comment by Kitteh6660** [comment]
Thank you, I will get around to revamping the door IDs and recipes to match. Hope to expect this change in Fabric and Forge.

**Comment by Kitteh6660** [comment]
Should be resolved in version 2.3.0 of the mod for 1.19.2.

**Comment by pastellexists** [comment]
When can we expect this change on Fabric? I can't seem to find 2.3.0 for Fabric.

**Comment by Kitteh6660** [comment]
Fabric versioning scheme is different. Rest assured, I will eventually get back to Fabric version and port the changes over.
