### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NotIntruder** [Kitteh6660/DramaticDoors#33]
While running on a Forge 1.19.2 server: 
![image](https://user-images.githubusercontent.com/86674642/229206963-d55cc8bf-f1e0-47a8-a31b-7693b6e5e914.png)

**Comment by Kitteh6660** [comment]
That must be one of the stray BYG recipes. I may get that removed.

**Comment by NotIntruder** [comment]
Thanks

**Comment by Kitteh6660** [comment]
Should be resolved in mod version 2.3.0 as that recipe advancement is now removed.
