### ISSUE TITLE
[REQUEST] configs to disable registering tall doors by mod

### ISSUE THREAD

**Issue by 800020h** [Kitteh6660/DramaticDoors#34]
**Is your feature request related to a problem? Please describe.**
extra unnecessary block states, and items in REI 

**Describe the solution you'd like**
configs to disable the compat for mods you don't have in the pack
(would also work for mods you do have, and maybe even minecraft)

**Describe alternatives you've considered**

**Additional context**

**Comment by Kitteh6660** [comment]
I am currently working on that. The next update will conditionally register doors for 5 mods.

Those are as following:

* Chipped
* Macaw's Doors
* ManyIdeas Doors
* Oh the Biomes You'll Go
* Mo' Shiz

I've even gotten around to make sure built-in data packs are dynamically enabled based on what mods are installed which contains recipes, advancements, and loot tables.

The change can result in reduction of 70% thus significantly cutting down on unused block states.

**Comment by 800020h** [comment]
sounds good

**Comment by Kitteh6660** [comment]
Should be implemented in version 2.3.0 and it's done automatically.

**Comment by Dr-WeiAL** [comment]
Does version 2.3.5 still seem to have this problem? I see a lot of doors in EMI for mods that I don't have installed
