### ISSUE TITLE
[BUG] Right Clicking Lead Short Door crashes the game

### ISSUE THREAD

**Issue by Numerosityy** [Kitteh6660/DramaticDoors#37]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove Dramatic Doors to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.
 * https://bytebin.lucko.me/kRdBKLQ56m

**Important Information**
Minecraft Version: **1.19.2**
Mod Loader System: **Forge** (Forge or Fabric)
DramaticDoors Version: **2.3.2**

**Describe the bug**
When right clicking on a Lead Short Door, the game crashes.

**To Reproduce**
Right click on a Lead Short Door (possibly a few times)

**Expected behavior**
For the game to... not crash? lol

**Comment by Kitteh6660** [comment]
I've found the issue, apparently it tries to open both doors and thus crashes. Hang on tight, a fix is on its way!

**Comment by Numerosityy** [comment]
Awesome, thanks for the reply! I appreciate your work ^^

**Comment by Kitteh6660** [comment]
Should be fixed in 2.3.3.
