### ISSUE TITLE
[BUG] Latest version (1.19.2) breaks mineable/axe tag

### ISSUE THREAD

**Issue by FluffiKiki** [Kitteh6660/DramaticDoors#38]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove Dramatic Doors to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Important Information**
Minecraft Version: 1.19.2
Mod Loader System: Forge 43.2.0-8
DramaticDoors Version: 2.3.1-2.3.2

**Describe the bug**
When on the two tested versions, the mineable/axe tag disappears, leading to all logs, wood, planks, and other applicable blocks unable to be broken properly with an axe. Screenshot shows missing tag w/ Dramatic Doors installed. Note: Downgrading to 2.3.0 fixes this. 

**To Reproduce**
Installed versions 2.3.1 or 2.3.2; attempted to break wood faster with axe.

**Expected behavior**
Axes should be able to break any wood or wood-related item quickly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/42556991/235281440-e6e6a8b2-16c7-4749-b5df-7a724bfcc973.png)

**Comment by Kitteh6660** [comment]
Thanks for reporting, I will look into fixing it!

**Comment by Kitteh6660** [comment]
Released a new update, does it fix the broken tags?

**Comment by FluffiKiki** [comment]
Tested, newest version does fix it. Thanks so much!
