### ISSUE TITLE
[REQUEST] Move wood door stonecutter recipes to Woodworks' Sawmill (if installed)

### ISSUE THREAD

**Issue by Numerosityy** [Kitteh6660/DramaticDoors#39]
**Is your feature request related to a problem? Please describe.**
Not really a problem as much as a possible improvement. Would be a nice feature if possible

**Describe the solution you'd like**
If Woodworks is installed, all wooden door recipes get moved to the Sawmill block

**Describe alternatives you've considered**
Dealing with it as is? Idk, it just doesn't really make sense to cut wood with a stonecutter.

**Additional context**
N/A

**Comment by Kitteh6660** [comment]
This is something I've actually considered and I think it can be done. It will take time.

When only Dramatic Doors is installed and Woodworks isn't, stonecutter will still be used to cut wooden doors into short doors, but when the mod is installed, it can change the recipe.

Stonecutter will still be used for cutting stone, metal, and glass doors however.

**Comment by Kitteh6660** [comment]
The change will eventually go live in mod version 2.3.4 of Dramatic Doors.

**Comment by Kitteh6660** [comment]
Now implemented in mod version 2.3.4
