### ISSUE TITLE
[BUG] Environmental Cherry Doors and Vanilla Cherry Doors mismatched

### ISSUE THREAD

**Issue by jogurciQ** [Kitteh6660/DramaticDoors#41]
Minecraft Version: 1.19.2
Mod Loader System: Forge
DramaticDoors Version: 2.3.3

Environmental's Short Cherry Door item texture uses the vanilla Short Cherry Door item texture. Environmental's Tall Cherry Door block texture uses the vanilla Tall Cherry Door block texutre

1. Install Environmental
2. Make a new world (preferably in creative mode)
3. Get a Short Cherry Door and a Tall Cherry Door
4. Look at the Short Cherry Door texture in your inventory and place a Tall Cherry Door in your world

**Expected behavior**
The observed textures should match the ones from Environmental

**Screenshots**
![obraz](https://user-images.githubusercontent.com/58147676/235637122-8547141b-57ff-4af6-aeec-e37ac68b17de.png)

**Comment by Kitteh6660** [comment]
Thank you, I will get that fixed shortly!

**Comment by Kitteh6660** [comment]
Now fixed in mod version 2.3.4
