### ISSUE TITLE
[REQUEST] Gardens of the Dead Support for Fabric?

### ISSUE THREAD

**Issue by An-thracene** [Kitteh6660/DramaticDoors#44]
I notice that you support Gardens of the Dead in #13. But it seems that the support is only for Forge.
So could you support it on Fabric? Thanks very much!

**Comment by Kitteh6660** [comment]
I can add support for that!

**Comment by Kitteh6660** [comment]
Implemented in version 2.0.0 of Dramatic Doors for Fabric on 1.19.2!

Support will also be ported over to 1.19.4 and 1.20 as futureproofing.
