### ISSUE TITLE
[REQUEST] Support for the Mystic's Biomes mod

### ISSUE THREAD

**Issue by JustVibin247** [Kitteh6660/DramaticDoors#45]
https://www.curseforge.com/minecraft/mc-mods/mystics-biomes

Mystic's Biomes adds 3 unique biomes to the game. including 3 new doors for the new wood types

![2023-05-30_14 28 21](https://github.com/Kitteh6660/DramaticDoors/assets/72247863/4b80bc92-09a8-4095-aa0d-5f9229b69b01)

**Comment by Kitteh6660** [comment]
I can definitely look into that! :)
