### ISSUE TITLE
[BUG] Crashing with Every Compat. (2.4.9a)

### ISSUE THREAD

**Issue by Diogoess** [Kitteh6660/DramaticDoors#46]
**Important Information**
Minecraft Version: 1.19.2
Mod Loader System: Forge (43.2.13)
DramaticDoors Version: DramaticDoors-Forge-1.19.2-2.1.9 (later versions would have the the startup freeze before the game opens)

**Describe the bug**
When the mod every compat is present (using the latest version), game is crashing. 
https://gist.github.com/Diogoess/7cfa1a19e67ff1bd57e57fccd95987b0

**To Reproduce**
Have every compat and dramatic doors installed

**Expected behavior**
The game starting with both mods.

**Screenshots**
Couldn't find this in the crash report, but it appeared in the log, attaching a screenshot.
![SCREENSHOT](https://github.com/Kitteh6660/DramaticDoors/assets/127145790/f964d9db-4e9a-489a-bd89-fac599d8e07e)

**Comment by Kitteh6660** [comment]
For later versions, have you tried allocating more RAM?

I may also look into it and try to investigate the issue.

**Comment by Diogoess** [comment]
Alright, so I tried opening up the game with the latest version, as suggested, and with 15gb ram allocated, it still isn't opening. I'm sending the log at the end.

Things I noticed in the log and tried but didn't work:
Removing the optional dependencies.
Removing the mods in the last line of the log when it got stuck, ends up just showing another mod.

Could it be the forge version? 

https://gist.github.com/Diogoess/529acad844f74c2d0ea0df138a2622bc

**Comment by Diogoess** [comment]
Ok, after going through the whole modpack, I found the problem. 
The good news is that I don't think the problem is every compat.
It's the version I have of Regions Unexplored (0.3.1). The issue is that because the next version (0.4.x) removes and adds some biomes, It WILL mess up my world if I update. When I remove this mod it, and after updating Abundant atmosphere, the game runs normally.
When I downgrade dramatic doors, it becomes incompatible with the newest Every Compat.
When I downgrade Every Compat, it becomes incompatible with other mods on the list.

Is there a way around making the newest Dramatic Doors still compatible with older (Optional) Dependencies?

**Comment by Kitteh6660** [comment]
Unfortunately, there generally isn't a way. You could try making a new world however.

**Comment by Kata1337** [comment]
I have run into this same problem with DD 3.1.0 or higher on MC 1.20.1 and Forge 47.2.0.  MC crashes on launch with Every Compat failing to load correctly.  The error is java.lang.reflect.InvocationTargetException: null

This is with no other mods installed, just the required Moonlight Lib.

Reverting DD to 3.0.3 fixes the problem and everything loads correctly.  Not sure if the fault is with DD or Every Compat, but there it is.

**Comment by Kitteh6660** [comment]
It's due to the big code rewrite on Dramatic Doors that broke compat. Every Compat is being updated to work with the latest version.

**Comment by Kata1337** [comment]
That's good to hear, thanks!

**Comment by Kitteh6660** [comment]
Every Compat should be updated on 1.19.2 to work with the latest version of Dramatic Doors for 1.19.2.
