### ISSUE TITLE
[BUG] Doors with uninstalled mods registered

### ISSUE THREAD

**Issue by Dr-WeiAL** [Kitteh6660/DramaticDoors#48]
**Important Information**
Minecraft Version: **1.19.2**
Mod Loader System: **Forge**
DramaticDoors Version: **2.3.5**

**Describe the bug**
I discovered while using EMI that the mod registered a lot of doors for mods that I didn't install

**Expected behavior**
These doors should not be registered

**Screenshots**
![image](https://github.com/Kitteh6660/DramaticDoors/assets/47446553/8f65eae2-acce-4061-994e-ddbf535d0d82)

**Comment by Kitteh6660** [comment]
Unfortunately, this is the result of balancing the number of data packs, and I don't want to clutter the data packs. There are already up to 9 built-in data packs that have recipes, loot tables, and advancements.

**Comment by Dr-WeiAL** [comment]
Uh... so this problem can't be solved for now?

**Comment by Kitteh6660** [comment]
I gave those doors tags so you could try using KubeJS to hide doors from EMI. Heck, there are categories.
