### ISSUE TITLE
Dramatic Doors causing world ID corruption

### ISSUE THREAD

**Issue by Zelioth** [Kitteh6660/DramaticDoors#5]
Howdy, I'll try to explain this issue, how I found it, versions, and what really happened or what may cause it.

So I am the creator of "Friends United" A mod pack that is fairly new and large for 1.19.2. I have used Dramatic Doors since you released it for 19.2 and everything has been perfect. I am currently processing an update for my mod pack which will be version 4.0.3. I updated and added a few mods to my mod pack while also removing a few mods to improve performance. One of those updates were Dramatic Doors. So updating to version 2.0.6 for 1.19.2 and tested the client side, everything was fine. Before pushing the update and rolling it to my public servers I tested it locally and found that the worlds were corrupted so bad that they would be unplayable. After starting over and updating EACH mod one by one, group by group I finally came down to removing Dramatic Doors from the pack, generating a new server entirely (World, config) that the world would generate perfectly fine without any issues but when having Dramatic Doors in the pack it would just destroy the world. 

So why do I think this happened.  I have been testing for a few days and I am not really sure but it could be a compatibility issues somewhere. I know Double Doors was installed and I removed it because quark added this feature and it was messing with doors so much that you couldn't even right click to open them. I can provide a picture and logs as to how things generate when they are messed up but for more info I would need you to reach out on my discord or your discord and I'd work right beside ya at figuring the issue out in case anyone else is suffering from it. It has taken FOREVER to find the issue and finally finding it I would like to help fix it if it is an issue with the mod itself or a compatibility error.

Minecraft 1.19.2 
Forge Tested versions  43.1.64 to 43.2.1.

Logs 
[latest.log](https://github.com/Kitteh6660/DramaticDoors/files/10297977/latest.log)

[debug.log](https://github.com/Kitteh6660/DramaticDoors/files/10297976/debug.log)

Friends United DIscord. 
https://discord.gg/uHeaPzKNVf

**Comment by Zelioth** [comment]
I'd like to add the version 4.0.2 Friends United was running 2.1.3 of your mod. It seemed perfectly fine and never caused this issue but it seems the newest version does cause this issue

![Dramatic Doors](https://user-images.githubusercontent.com/77481431/209420928-8a00cc10-afbc-49b7-b59e-f8e2158c4d1e.jpg)

**Comment by Zelioth** [comment]
I'd like to retract my last statement. IT appears to now do it no matter the version of DD. I'm unsure what mod update changed compatibility with this or what it's having issues with but removing the mod DD fixes the world

**Comment by Kitteh6660** [comment]
That is an odd issue. I will have to look into it.

Do keep in mind that there's waterlogging property that you can turn on or off. You can disable waterlogging and see if that fixes the issues.

**Comment by nanonestor** [comment]
I can also confirm having this issue however having different mods/blocks the look of the corrupted world was different.  It looked like groups of blocks somehow had their ID names/numbers all jumbled up from the correct blocks.
