### ISSUE TITLE
[REQUEST] 3 blocks wide doors?

### ISSUE THREAD

**Issue by Marius-jj** [Kitteh6660/DramaticDoors#50]
Would it be possible to add Dramatic Doors that also are 3 blocks wide? so 3x3 in size? Would be cool for some castle builds!

**Comment by Kitteh6660** [comment]
You could try Many Ideas Doors if you are looking for something like that.

**Comment by Marius-jj** [comment]
Thanks, that mod had some 3x3 doors, but was kinda just looking for vanilla doors but in 3x3 size. But thanks!
