### ISSUE TITLE
[REQUEST] Support for the Wilder Wild mod?

### ISSUE THREAD

**Issue by xofSpook** [Kitteh6660/DramaticDoors#51]
https://modrinth.com/mod/wilder-wild/

Wilder Wild adds 3 new doors to the game: Baobab, Cypress and Palm

![2023-07-24_09 10 46](https://github.com/Kitteh6660/DramaticDoors/assets/140379563/10bc2b1a-cd5a-4745-bf24-8185d064477a)

Would be really cool to see added in an update, the mod is very well integrated into vanilla.

**Comment by Kitteh6660** [comment]
Thank you, I can do that!

**Comment by xofSpook** [comment]
Thanks for adding support!
