### ISSUE TITLE
[BUG] Crash with newest Macaw's Doors 1.18.2

### ISSUE THREAD

**Issue by Auuki** [Kitteh6660/DramaticDoors#52]
**Important Information**
Minecraft Version: **1.18.2**
Mod Loader System: **Forge 40.2.9**
DramaticDoors Version: **1.18.2-2.3.1_2**

**Describe the bug**
Macaw's Doors crash when DramaticDoors is enabled. I'm reporting it here because I saw Kitteh6660 fixed it for other MC versions but not this one.

**To Reproduce**
- Have newest Macaw's Doors and Dramatic Doors enabled
- Start the game

**Expected behavior**
The game loads to main menu
[crash-2023-08-07_14.07.14-fml.txt](https://github.com/Kitteh6660/DramaticDoors/files/12279555/crash-2023-08-07_14.07.14-fml.txt)

**Comment by Kitteh6660** [comment]
I will get that fixed eventually!

**Comment by Kitteh6660** [comment]
The fix has been backported and will be on mod version 2.3.1_3.

**Comment by Auuki** [comment]
Yes, I am aware of that. Thank you.
