### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Numerosityy** [Kitteh6660/DramaticDoors#53]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove Dramatic Doors to see if they are causing the issue before reporting. ✔️
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Important Information**
Minecraft Version: 1.19.2
Mod Loader System: Forge
DramaticDoors Version: 2.3.7_2

**Describe the bug**
Missing texture/model on vanilla doors and fence gates

**To Reproduce**
Steps to reproduce the behavior: Unsure

**Expected behavior**
Vanilla doors/fence gates look normal

**Screenshots**
![image](https://github.com/Kitteh6660/DramaticDoors/assets/114539001/c7bc4390-5fba-441f-aa7e-4c2f4e84c9a1)

**Comment by Numerosityy** [comment]
Log: https://paste.atlauncher.com/view/6e05994d-8f65-422f-b6b6-0bde8818c864

**Comment by Kitteh6660** [comment]
It's because of Statement mod. The chat message even indicates so. You can try any of the following methods:

1. Remove Statement mod.
2. Turn off waterlogging in the config file.
3. Press F3+T to reload resource pack, the issue should go away temporarily.
