### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by moxg22** [Kitteh6660/DramaticDoors#54]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove Dramatic Doors to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Important Information**
Minecraft Version: **1.19.2**
Mod Loader System: **Fabric** (Forge or Fabric)
DramaticDoors Version: **2.0.1**

**Describe the bug**
The bug causes the world in multiplayer only to glitch and replace blocks with other blocks.  As seen in the attached screenshot.

**To Reproduce**
Steps to reproduce the behavior: Be in multiplayer. With these mods 
cloth API 4.0.65
cloth config 8.3.103
Dramatic Doors 1.19.2 2.0.1
Fabric API 0.76.0 1.19.2
Macaw Doors 1.1.0 1.19.2
https://www.curseforge.com/minecraft/modpacks/chronost-incorporated/files/4673955 (the modpack that is in it)

**Expected behavior**
The world to not have blocks randomly replaced.

**Screenshots**
Seems to only happen in multiplayer.
![image_2023-08-12_225548392](https://github.com/Kitteh6660/DramaticDoors/assets/122064868/a1e67cd6-6bd8-4dc0-b513-4959aa3e092a)
![image_2023-08-12_230120028](https://github.com/Kitteh6660/DramaticDoors/assets/122064868/d87fee8f-aabd-41df-8be0-38b28f0c5c60)

**Comment by Kitteh6660** [comment]
Try turning off waterlogging for both block types in the config file and see if that fixes the issue.

**Comment by moxg22** [comment]
didn't fix it not sure what is going on

**Comment by Kitteh6660** [comment]
Make sure to do it for both client and server.

**Comment by moxg22** [comment]
I installed https://www.curseforge.com/minecraft/mc-mods/statement and it fixed the problem sorry for bothering you
