### ISSUE TITLE
[REQUEST] Config to disable non-vanilla door recipes

### ISSUE THREAD

**Issue by spencerfrost** [Kitteh6660/DramaticDoors#56]
Would it be possible to have a config file for Dramatic Doors that allows us to disable the doors from mods we aren't using. As is, dramatic doors takes up one of five pages in my REI menu. Just a simple toggle for each mod that has doors in this mod would be amazing! Not a huge issue, but would be a great QoL feature! Thanks for the mod!

![image](https://github.com/Kitteh6660/DramaticDoors/assets/34923439/121404bd-180f-4b14-be2e-5a1aed924dae)

**Comment by spencerfrost** [comment]
Just found the customized filtering! This is a fine solution. Feel free to close this, but the config still might be a nice feature.

![image](https://github.com/Kitteh6660/DramaticDoors/assets/34923439/0a7db917-8178-4087-9233-4b90c68d028c)

**Comment by Kitteh6660** [comment]
You indeed can use tags, that's why the doors are tagged.

**Comment by Kitteh6660** [comment]
QuiFabrge now uses a much more modular registry, even more modular. I feel confident I can close this now.
