### ISSUE TITLE
DramaticDoors-QuiFabrge-1.20.1-3.0.0.jar tagged as forge, will not load in forge.

### ISSUE THREAD

**Issue by ProsperCraft** [Kitteh6660/DramaticDoors#57]

**Comment by Kitteh6660** [comment]
You need [Sinytra Connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector) and [Forgified Fabric API](https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api).

**Comment by ProsperCraft** [comment]
This would bloat my pack by two more mods when I am trying to pair down the mods, I guess I can not update, or just remove it.

**Comment by Kitteh6660** [comment]
You can continue using Dramatic Doors Forge 1.20.1-2.3.8.

Technically, version 3.0 of the mod does not really add anything new content-wise, it's a merge of Forge and Fabric assets and compats. On the upside, mod version 3.0 will also have compats for Fabric mods.

**Comment by Kitteh6660** [comment]
I am working on a better solution and I have found it.

Version 3.1.0 will no longer require Sinytra Connector.
