### ISSUE TITLE
[BUG] missing short echo door recipe

### ISSUE THREAD

**Issue by edensiiln** [Kitteh6660/DramaticDoors#60]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove Dramatic Doors to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Important Information**
Minecraft Version: **1.20.1**
Mod Loader System: **Fabric**
DramaticDoors Version: **1.20.1-3.0.3**

**Describe the bug**
with Deeper and Darker installed, there is a missing stonecutter recipe for a short echo door added by this mod, created from Deeper and Darker's normal echo door.

**To Reproduce**
- Load the game with Deeper and Darker installed
- place an echo door from that mod into a stonecutter, or inspect it or the short echo door in a mod like REI, and note the missing recipe

**Expected behavior**
the short echo door would be craftable

**Screenshots**
n/a

**Comment by Kitteh6660** [comment]
Fixed as of version 3.1.0 of Dramatic Doors for 1.19.2. Fix will be ported over to 1.20.1.
