### ISSUE TITLE
[REQUEST] Aurora's Decorations (Azalea & Jacaranda)

### ISSUE THREAD

**Issue by sisby-folk** [Kitteh6660/DramaticDoors#62]
**Is your feature request related to a problem? Please describe.**
I'd like to use Dramatic Doors in a modpack with [Aurora's Decorations](https://modrinth.com/mod/aurorasdecorations).

**Describe the solution you'd like**
I'd like dramatic doors for the Azalea [top](https://github.com/LambdAurora/AurorasDecorations/blob/1.20/src/main/resources/assets/aurorasdeco/textures/block/azalea_door_top.png) [bottom](https://github.com/LambdAurora/AurorasDecorations/blob/1.20/src/main/resources/assets/aurorasdeco/textures/block/azalea_door_bottom.png) [item](https://github.com/LambdAurora/AurorasDecorations/blob/1.20/src/main/resources/assets/aurorasdeco/textures/item/azalea_door.png) and Jacaranda [top](https://github.com/LambdAurora/AurorasDecorations/blob/1.20/src/main/resources/assets/aurorasdeco/textures/block/jacaranda_door_top.png) [bottom](https://github.com/LambdAurora/AurorasDecorations/blob/1.20/src/main/resources/assets/aurorasdeco/textures/block/jacaranda_door_bottom.png) [item](https://github.com/LambdAurora/AurorasDecorations/blob/1.20/src/main/resources/assets/aurorasdeco/textures/item/jacaranda_door.png) wood types.

**Additional context**
We just haven't been using DD in our modpack so far as a solution, but considering we've had some requests for it i figured I might as well file this one as a formality.
Aurora's Decorations is LGPLv3, so explicit reuse and modification permission for those 6 textures in an MIT project would need to come from @LambdAurora as well.

**Comment by Kitteh6660** [comment]
I can potentially look into it.

I will ask for permission.
