### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VenusVesper** [Kitteh6660/DramaticDoors#63]
I was starting up my modpack with this mod installed obvi (1.19.2, forge 43.3.0) there are many other mods installed (316) and my game crashed as it was loading :( I tried a couple more times to load it but to no avail. 
I removed the dramatic doors mod from the modpack and it loaded as intended. 

Is there a dependency im missing that didnt install automatically??? Because I really love this mod

**Comment by Kitteh6660** [comment]
What version of Dramatic Doors do you have installed?

**Comment by VenusVesper** [comment]
Ah, i have every compat installed

**Comment by VenusVesper** [comment]
I’ll just do the waiting

**Comment by Kitteh6660** [comment]
The newest version of Every Compat should be working.
