### ISSUE TITLE
[Startup Crash] The validated object is null

### ISSUE THREAD

**Issue by A5ho9999** [Kitteh6660/DramaticDoors#64]
**Important Information**
Minecraft Version: **1.20.1**
Mod Loader System: **Fabric 0.14.23**
DramaticDoors Version: **https://modrinth.com/mod/dramatic-doors/version/1.20.1-3.1.0**

**Describe the bug**
Crashed on startup due to null stuff, probably conflicted with another mod or something.
Log: https://gist.github.com/80e1d956426a8a01c8fea296616f8eab.git

Edit: Version 3.0.3 works fine

**To Reproduce**
Can't really say, if it's a normal crash then just start the game, other than that not sure.

**Expected behavior**
Start up normally

**Screenshots**

**Comment by Kitteh6660** [comment]
It has something to do with Supplementaries compat since it's the only compat to add a block entity. I will get that fixed.

**Comment by Kitteh6660** [comment]
I've uploaded mod version 3.1.0_1, does it fix the crash?

**Comment by A5ho9999** [comment]
I won't be able to check until later, but will let you know! Thanks

**Comment by A5ho9999** [comment]
Sorry for the delay, appears to be fixed now yes. Thank you
