### ISSUE TITLE
[REQUEST] Tag doors with #minecraft:doors

### ISSUE THREAD

**Issue by LazyDope** [Kitteh6660/DramaticDoors#65]
**Is your feature request related to a problem? Please describe.**
Tag doors with the #minecraft:doors tag so that they are recognized as such for tag targets for chunk protection and recipes, rather than needing to give specifics exceptions for the mod specifically.

**Describe the solution you'd like**
Add the tag to all doors when they are included.

**Comment by Kitteh6660** [comment]
I honestly don't know, as the short and tall doors do not extend from DoorBlock so there can be some weirdness and potential crashes, as they don't use the half property. Even though they do have hinge, orientation, powered, and open.

There are tags: dramaticdoors:tall_doors and dramaticdoors:short_doors

You can try using those..

**Comment by LazyDope** [comment]
I see, thanks for that note about the tags provided by the mod
