### ISSUE TITLE
DramaticDoors-QuiFabrge-1.19.2-3.1.2.jar causes Mod Pack launch Failure

### ISSUE THREAD

**Issue by Fade-Alchemist** [Kitteh6660/DramaticDoors#68]
Minecraft Version: 1.19.2
Mod Loader System: Fabric 0.14.23
DramaticDoors Version: DramaticDoors-QuiFabrge-1.19.2-3.1.2.jar

The most recent version of Dramatic Doors causes the mod pack to fail to launch

[2023-10-30-7.log.gz](https://github.com/Kitteh6660/DramaticDoors/files/13199681/2023-10-30-7.log.gz)

**Comment by Kitteh6660** [comment]
I'll look into fixing it!

**Comment by Wilevar** [comment]
Same. 3.1.0_1 works fine client and server, but 3.1.2 and 3.1.3 both cause failure to start when loading a server.
All versions work fine in my modpack on Client, only the server seems to have problems.

**MC Version:** 1.20.1
**Fabric Server Version:** (1.20.1) 0.14.23
[2023-11-01-3.log.gz](https://github.com/Kitteh6660/DramaticDoors/files/13232461/2023-11-01-3.log.gz)

**Comment by Kitteh6660** [comment]
It seems the issue is only on server on Fabric. I will have to look into fixing it.

**Comment by Kitteh6660** [comment]
I've uploaded mod version 1.19.2-3.1.3, I hope it should fix. If not, let me know!

**Comment by raws** [comment]
3.1.3_1 is working as advertised on 1.20.1 for me 🎉 Thanks for the quick fix!
