### ISSUE TITLE
[BUG] Dramatic Doors (dramaticdoors) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by ModernGamingWorld** [Kitteh6660/DramaticDoors#70]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove Dramatic Doors to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Important Information**
Minecraft Version: **1.19.2*
Mod Loader System: **Forge** (Forge or Fabric)
DramaticDoors Version: **DramaticDoors-QuiFabrge-1.19.2-3.1.3**

**Describe the bug**
java.lang.RuntimeException: PartialModel 'dramaticdoors:block/create/tall_andesite_door_fold_left' loaded after ModelEvent.RegisterAdditional

**To Reproduce**
Not sure, just launched my game after updating some mods and it crashed on load up

**Expected behavior**
A quick fix so I can post my new update for end users to enjoy!!!!

**Screenshots**
![2023-11-02_16 30 57](https://github.com/Kitteh6660/DramaticDoors/assets/75923060/f209b87f-6df2-4880-9771-e17d0b20d25c)

[crash-2023-11-02_16.30.43-fml.txt](https://github.com/Kitteh6660/DramaticDoors/files/13244823/crash-2023-11-02_16.30.43-fml.txt)

**Comment by Kitteh6660** [comment]
I'm gonna go back and keep trying to fix!

**Comment by ModernGamingWorld** [comment]
okay

**Comment by ModernGamingWorld** [comment]
This is with Create and forge btw

**Comment by Kitteh6660** [comment]
A new version is being uploaded, it should be labeled as 1.19.2-3.1.3_1. Hopefully it should fix the issues.

**Comment by Kitteh6660** [comment]
Closed as there are no new replies and everything should be working now, hopefully.
