### ISSUE TITLE
[BUG] Incompatibility with ModernFix's Dynamic Resource feature if also using Create

### ISSUE THREAD

**Issue by mosharky** [Kitteh6660/DramaticDoors#71]
**Important Information**
Minecraft Version: **1.20.1**
Mod Loader System: **Forge**
DramaticDoors Version: **3.1.3_2**

**Logs**
[latest.log](https://mclo.gs/8obPnfJ)
[crash report](https://mclo.gs/6yMTFWT)

**Describe the bug**
If using ModernFix's [Dynamic Resources feature](https://github.com/embeddedt/ModernFix/wiki/Dynamic-Resources-FAQ), and if also using Create, the game crashes because of Dramatic Doors.

**To Reproduce**
1. Create an instance with just Create, Dramatic Doors, and ModernFix
2. In the configs, open the `modernfix-mixins.properties` and set `mixin.perf.dynamic_resources` to true
3. Launch the game and crash

**Comment by Kitteh6660** [comment]
I've uploaded a new version, does it fix the crashes?

**Comment by mosharky** [comment]
Seems to be fixed! Thanks!
