### ISSUE TITLE
[BUG]  Crashes with every QuiFabrge (compatible?)

### ISSUE THREAD

**Issue by Nejc5009** [Kitteh6660/DramaticDoors#73]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove Dramatic Doors to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Important Information**
Minecraft Version: 1.19.2
Mod Loader System: Forge 43.3.5
DramaticDoors Version: DramaticDoors-QuiFabrge-1.19.2-3.1.3_1

**Describe the bug**
Crashes when starting the game

**Screenshots**
https://gist.github.com/Nejc5009/6dae44dc76f5d724780091e3b27398bb

**Comment by Kitteh6660** [comment]
It could be a conflicting mod that adds waterlogged property. I may have a look into it and find out the cause.

**Comment by Nejc5009** [comment]
Yes, I disable Blockcarpentry and everything worked.

I disable only Waterloggable Fence Gates and still crashes.

I disable only Waterloggable Doors and still crashes.

I disable Fence Gates and Doors and still crashes, disabled via "configured"
![111](https://github.com/Kitteh6660/DramaticDoors/assets/107282638/c0445aa5-344b-463f-bee7-10ea17b6b0ad)

**Comment by Kitteh6660** [comment]
Got it, I will get that fixed!

**Comment by Kitteh6660** [comment]
Version 3.1.4 should hopefully fix the issue.

**Comment by Nejc5009** [comment]
Thank you!
