### ISSUE TITLE
[BUG] Causing crash in dev env without Create

### ISSUE THREAD

**Issue by SettingDust** [Kitteh6660/DramaticDoors#80]
**Important Information**
Minecraft Version: 1.20.1
Mod Loader System: Fabric
DramaticDoors Version: 1.20.1-3.1.5

**Describe the bug**
https://github.com/Kitteh6660/DramaticDoors/blob/master/common/src/main/java/com/fizzware/dramaticdoors/compat/Compats.java#L313-L315

It makes the mod depends on this mod have to depend on the extra mods.

**Comment by Kitteh6660** [comment]
I will look to get this fixed!

**Comment by Kitteh6660** [comment]
It will be fixed in mod version 3.2.0 for 1.20.1. Can it be replicated with 3.2.0?
