### ISSUE TITLE
EveryCompat door cannot be crafted

### ISSUE THREAD

**Issue by vivagabe** [Kitteh6660/DramaticDoors#82]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove Dramatic Doors to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Important Information**
Minecraft Version: 1.20.1
Mod Loader System: Forge
DramaticDoors Version: 3.1.5

**Describe the bug**
EveryCompat doors (from macaws doors) show up in JEI but do not have a recipe

**To Reproduce**
try to craft everycompat door from macaw

**Expected behavior**
craft tall door from everycompat macaw

**Screenshots**
n/a

**Comment by Kitteh6660** [comment]
It appears to be on EveryCompat end. Both the doors and the tall doors are registered by EveryCompat.
