### ISSUE TITLE
[REQUEST] Immersive Weathering support

### ISSUE THREAD

**Issue by Abbie5** [Kitteh6660/DramaticDoors#89]
https://modrinth.com/mod/immersive-weathering

This mod adds stages of rusting (exposed, weathered and rusted) to iron doors, as well as waxed variants. Please add short and tall variants of these doors to this mod!

**Comment by Kitteh6660** [comment]
Mod support implemented as of Dramatic Doors version 3.2.2 for MC 1.20.1! :)
