### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zc1108aaa** [Kitteh6660/DramaticDoors#92]
[crash-2024-05-27_00.39.55-client.txt](https://github.com/Kitteh6660/DramaticDoors/files/15448250/crash-2024-05-27_00.39.55-client.txt)

**Comment by Kitteh6660** [comment]
Thank you, I will update to fix support for Panda's Extra Details.

**Comment by Kitteh6660** [comment]
Should be fixed in 3.2.2. Keep in mind that short and tall doors will no longer animate until a workaround can be looked into.
