### ISSUE TITLE
[BUG] Crash with Dramatic Doors 3.2.2

### ISSUE THREAD

**Issue by lxly9** [Kitteh6660/DramaticDoors#93]
https://gist.github.com/lxly9/90029b2c669a06513a6ae08065dec0a2

Minecraft Version: **1.20.1**
Mod Loader System: **Quilt**
DramaticDoors Version: **3.2.2**

**Describe the bug**
When installing the newest version of DD and starting the game, first a resource reload fail happens and when trying to join/create a world the game crashes.

**Comment by Kitteh6660** [comment]
Thank you, I will look to get this fixed!

**Comment by Kitteh6660** [comment]
It must be Immersive Weathering. A new version of Dramatic Doors is being uploaded. 3.2.3 should hopefully fix that.
