### ISSUE TITLE
[BUG]Crashing with the mod: thingamajigs

### ISSUE THREAD

**Issue by TreeFight** [Kitteh6660/DramaticDoors#94]
When using with the mod thingamajigs, the game will crash.
Crash logs: https://gist.github.com/TreeFight/0e13709c7452b0a138a93894a1f6b58f
I can confirm the crash is caused by the incompatibility of dramatic doors and thingamajigs, I tested all my mod one by one. 

This is the link of the thingamajigs mod: https://www.curseforge.com/minecraft/mc-mods/blueys-thingamajigs

**Comment by Kitteh6660** [comment]
This is strange, the errors pointed to Sodium. I may need to investigate.

**Comment by TreeFight** [comment]
In case you don't know, I'm playing 1.20.1 version with forge. No optifine, cause I use xenon (which is embeddium with some upgrade) and occlus instead.

**Comment by TreeFight** [comment]
> This is strange, the errors pointed to Sodium. I may need to investigate.

In case you don't know, I'm playing 1.20.1 version with forge. No optifine, cause I use xenon (which is embeddium with some upgrade) and occlus instead.

**Comment by TreeFight** [comment]
I saw your Pull request. So should I just wait for thingmajigs to update? Or would you update dramatic doors recently?

**Comment by TreeFight** [comment]
> There is going to be a fix. I've created a PR over there: [roberttkahelin8/thingmajigs#15](https://github.com/roberttkahelin8/thingmajigs/pull/15)
> 
> For some reason, LockableDoor does not inherit all the properties from base door block, thus if any properties were added to base door, it will crash.
> 
> In the meantime, I could inject waterlogging.

I saw your Pull request. So should I just wait for thingmajigs to update? Or would you update dramatic doors recently?

**Comment by Kitteh6660** [comment]
It's a matter of waiting for Thingamajigs to update!
