### ISSUE TITLE
[BUG] Server fail to start when Dramatic Doors 3.2.2 and Immersive Weathering are installed.

### ISSUE THREAD

**Issue by Blugori** [Kitteh6660/DramaticDoors#96]
**Important Information**
Minecraft Version: **1.20.1**
Mod Loader System: **Forge 47.3.0**
DramaticDoors Version: **3.2.2**
Immersive Weathering : **2.0.1**
moonlight : **2.12.4**

**Describe the bug**
On client, everything's fine, but when installed on the server, it will fail to start.

**To Reproduce**
Install all specified mods on the server, launch the server.
/!\ I didn't test in a clean environment without any other mod. But, when using DramaticDoors 3.2.1 the server started, so I'm assuming it's not an issue with an other mod.

**Expected behavior**
I was expecting the server to start.

**Screenshots**
![image](https://github.com/Kitteh6660/DramaticDoors/assets/66573974/3654a429-778a-405d-be6c-c10d784b4a50)

**Comment by Kitteh6660** [comment]
The fix will go live in Dramatic Doors version 3.2.3.
