### ISSUE TITLE
[BUG] Aether Redux's Blightwillow Door variants are uncraftable

### ISSUE THREAD

**Issue by Not-February** [Kitteh6660/DramaticDoors#98]
**Important Information**
Minecraft Version: 1.20.1
Mod Loader System: Forge 47.3.0
DramaticDoors Version: 3.2.3

**Describe the bug**
I noticed the following in my log file, as well as the fact that these door variants are uncraftable. It looks like the recipe is referencing skyroot doors instead of blightwillow doors, so it's no wonder.

``[Render thread/ERROR] [net.minecraft.world.item.crafting.RecipeManager/]: Parsing error loading recipe dramaticdoors:tall_blightwillow_door: com.google.gson.JsonSyntaxException: Unknown item 'aether_redux:skyroot_door'``
``[Render thread/ERROR] [net.minecraft.world.item.crafting.RecipeManager/]: Parsing error loading recipe dramaticdoors:short_blightwillow_door: com.google.gson.JsonSyntaxException: Unknown item 'aether_redux:skyroot_door'``

**To Reproduce**
Have both Aether Redux + Dramatic Doors installed and check the logs for errors when you load a world.

**Expected behavior**
For blightwillow door variants to be craftable with blightwillow doors as intended.

**Comment by Kitteh6660** [comment]
The fix is planned to be in the next update for 1.20.1!

**Comment by Kitteh6660** [comment]
Fix is now live in mod version 3.2.5 hopefully!
